-----CHALLENGE 1-----Most Profiting Authors

---STEP 1---Calculate the royalties of each sales for each author

create temporary table STEP1_1
SELECT T.TITLE_ID, A.AU_ID, (T.PRICE * S.QTY * T.ROYALTY / 100 * TA.ROYALTYPER / 100) AS SALES_ROYALTY
FROM AUTHORS AS A
LEFT JOIN TITLEAUTHOR AS TA
ON A.AU_ID = TA.AU_ID
INNER JOIN TITLES AS T
ON TA.TITLE_ID = T.TITLE_ID
INNER JOIN SALES AS S
ON T.TITLE_ID = S.TITLE_ID;

---STEP 2---Aggregate the total royalties for each title for each author

create temporary table STEP1_2
SELECT TITLE_ID, AU_ID, SUM(SALES_ROYALTY) AS TOTAL_ROYALTIES FROM STEP1_1
GROUP BY TITLE_ID, AU_ID
ORDER BY AU_ID

---STEP 3---Calculate the total profits of each author

create temporary table STEP1_3
SELECT AU_ID, SUM(TOTAL_ROYALTIES + ADVANCE) AS TOTAL_PROFIT
FROM STEP1_2
INNER JOIN TITLES AS T
ON STEP1_2.TITLE_ID = T.TITLE_ID
GROUP BY AU_ID
ORDER BY TOTAL_PROFIT DESC
LIMIT 3



-----CHALLENGE 2-----Alternative Solution

---STEP 1---

SELECT T.TITLE_ID, A.AU_ID, (T.PRICE * S.QTY * T.ROYALTY / 100 * TA.ROYALTYPER / 100) AS SALES_ROYALTY
FROM AUTHORS AS A
LEFT JOIN TITLEAUTHOR AS TA
ON A.AU_ID = TA.AU_ID
INNER JOIN TITLES AS T
ON TA.TITLE_ID = T.TITLE_ID
INNER JOIN SALES AS S
ON T.TITLE_ID = S.TITLE_ID;

---STEP 2--- 

SELECT S1.TITLE_ID, S1.AU_ID, SUM(SALES_ROYALTY) AS TOTAL_ROYALTIES
FROM
(SELECT T.TITLE_ID, A.AU_ID, (T.PRICE * S.QTY * T.ROYALTY / 100 * TA.ROYALTYPER / 100) AS SALES_ROYALTY
FROM AUTHORS AS A
LEFT JOIN TITLEAUTHOR AS TA
ON A.AU_ID = TA.AU_ID
INNER JOIN TITLES AS T
ON TA.TITLE_ID = T.TITLE_ID
INNER JOIN SALES AS S
ON T.TITLE_ID = S.TITLE_ID) AS S1
GROUP BY S1.TITLE_ID, S1.AU_ID
ORDER BY S1.AU_ID

---STEP 3---

SELECT S2.AU_ID, SUM(S2.TOTAL_ROYALTIES + T.ADVANCE) AS TOTAL_PROFIT
FROM
(SELECT S1.TITLE_ID, S1.AU_ID, SUM(S1.SALES_ROYALTY) AS TOTAL_ROYALTIES FROM 
(SELECT T.TITLE_ID, A.AU_ID, (T.PRICE * S.QTY * T.ROYALTY / 100 * TA.ROYALTYPER / 100) AS SALES_ROYALTY
FROM AUTHORS AS A
LEFT JOIN TITLEAUTHOR AS TA
ON A.AU_ID = TA.AU_ID
INNER JOIN TITLES AS T
ON TA.TITLE_ID = T.TITLE_ID
INNER JOIN SALES AS S
ON T.TITLE_ID = S.TITLE_ID) AS S1
GROUP BY S1.TITLE_ID, S1.AU_ID
ORDER BY S1.AU_ID) AS S2
INNER JOIN TITLES AS T
ON S2.TITLE_ID = T.TITLE_ID
GROUP BY S2.AU_ID
ORDER BY TOTAL_PROFIT DESC
LIMIT 3



---CHALLENGE 3---

CREATE TABLE IF NOT EXISTS most_profiting_authors
SELECT S2.AU_ID, SUM(S2.TOTAL_ROYALTIES + T.ADVANCE) AS TOTAL_PROFIT
FROM
(SELECT S1.TITLE_ID, S1.AU_ID, SUM(S1.SALES_ROYALTY) AS TOTAL_ROYALTIES FROM 
(SELECT T.TITLE_ID, A.AU_ID, (T.PRICE * S.QTY * T.ROYALTY / 100 * TA.ROYALTYPER / 100) AS SALES_ROYALTY
FROM AUTHORS AS A
LEFT JOIN TITLEAUTHOR AS TA
ON A.AU_ID = TA.AU_ID
INNER JOIN TITLES AS T
ON TA.TITLE_ID = T.TITLE_ID
INNER JOIN SALES AS S
ON T.TITLE_ID = S.TITLE_ID) AS S1
GROUP BY S1.TITLE_ID, S1.AU_ID
ORDER BY S1.AU_ID) AS S2
INNER JOIN TITLES AS T
ON S2.TITLE_ID = T.TITLE_ID
GROUP BY S2.AU_ID
ORDER BY TOTAL_PROFIT DESC
LIMIT 3